name: latexmk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-example:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v3
      - name: Configure TeXLive
        run: sudo apt-get install texlive-full
      - name: Generate PDF
        run: |
          pdflatex --shell-escape --interaction=nonstopmode main
          biber main
          pdflatex --shell-escape --interaction=nonstopmode main
          pdflatex --shell-escape --interaction=nonstopmode main
      - name: Commit PDF
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add main.pdf
          git commit -m "[CI] Rebuild example"
          git push

